# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'msrsan'

menu:
- {name: 'Startup / VC', path: 'menu', url: 'startupVC'}
- {name: 'Productivity', path: 'menu', url: 'productivity'}
- {name: 'Growth', path: 'menu', url: 'growth'}
- {name: 'Chill', path: 'menu', url: 'chill'}
- {name: 'About', path: 'menu', url: 'about'}



# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link: 'mailto:marko@techstars.com'}
- {icon: 'facebook', link: 'https://www.facebook.com/msrsan'}
- {icon: 'twitter', link: 'https://twitter.com/msrsan'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/msrsan/'}
- {icon: 'instagram', link: 'https://www.instagram.com/msrsan/'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  previous_page: 'Older'
  next_page: 'Newer'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
google_analytics: 'UA-27948235-2'